### ISSUE TITLE
Module is Linux-only since 0.04 because of Test::MemoryGrowth

### ISSUE THREAD

**Issue by mauke** [jbarrett/MIDI-RtMidi-FFI#11]
In the 0.04 release, a test was added that unconditionally uses Test::MemoryGrowth: `t/05-grow.t`

Test::MemoryGrowth is Linux-specific: https://metacpan.org/release/PEVANS/Test-MemoryGrowth-0.04/source/Build.PL#L6

This limits the systems that MDI::RtMidi::FFI can be installed on. I would suggest either moving `05-grow.t` to `xt` (for author-only testing) or making the test optional (and skipping it if Test::MemoryGrowth can't be loaded).

**Comment by jbarrett** [comment]
Sorry for the delay in responding to this - completely missed it.

This should be resolved in 0.05. Many thanks for reporting!
